/**
 * Built-in character look template ("evelyn").
 *
 * Public source packs ship WITHOUT the bundled model (its licence forbids
 * redistribution), so this file carries only the *look* — lighting, camera,
 * idle, behaviour and lip-sync tuning. Imported characters inherit all of it
 * via `configFromProfile()`, which is why every import looks polished with
 * no hand tuning. In public builds (`VITE_ABxAG_PUBLIC=1`) the registry is
 * empty and the user imports their own model on first run.
 */
import type { CharacterConfig } from '../types';

export const evelynConfig: CharacterConfig = {
  id: 'evelyn',
  displayName: 'Evelyn',
  modelUrl: '/assets/characters/evelyn/model.pmx',
  textureMapUrl: '/assets/characters/evelyn/textures.json',
  scale: 1,
  groundOffset: 0,
  bones: {
    root: '全ての親',
    center: 'センター',
    groove: 'グルーブ',
    waist: '腰',
    lowerBody: '下半身',
    upperBody: '上半身',
    upperBody2: '上半身2',
    neck: '首',
    head: '頭',
    eyes: '両目',
    eyeL: '左目',
    eyeR: '右目',
    shoulderL: '左肩',
    shoulderR: '右肩',
    armL: '左腕',
    armR: '右腕',
    elbowL: '左ひじ',
    elbowR: '右ひじ',
    wristL: '左手首',
    wristR: '右手首',
    legL: '左足',
    legR: '右足',
    kneeL: '左ひざ',
    kneeR: '右ひざ',
    ankleL: '左足首',
    ankleR: '右足首',
  },
  morphs: {
    blink: 'まばたき',
    smileEyes: '笑い',
    visemeA: 'あ',
    visemeI: 'い',
    visemeU: 'う',
    visemeE: 'え',
    visemeO: 'お',
    visemeTalk: 'あ',
    mouthSmile: 'にこり',
    browSad: '困る',
    browUp: '驚き',
  },
  materialRoles: {},
  materialTuning: {},
  camera: {
    targetBone: '上半身2',
    targetOffset: 2.5,
    distance: 32,
    fov: 30,
    heightOffset: 0,
    parallax: 0.02,
    minDistance: 12,
    maxDistance: 80,
  },
  lighting: {
    keyIntensity: 1.15,
    keyColor: 0xfff2e6,
    keyAzimuth: 35,
    keyElevation: 48,
    fillIntensity: 0.42,
    fillColor: 0xdfe8ff,
    fillAzimuth: -42,
    fillElevation: 12,
    rimIntensity: 0.85,
    rimColor: 0xbfd4ff,
    rimAzimuth: 165,
    rimElevation: 22,
    hairLightIntensity: 0.7,
    hairLightColor: 0xfff6ea,
    frontFillIntensity: 0.35,
    frontFillColor: 0xffffff,
    face: {
      keyAzimuth: 28,
      keyElevation: 18,
      keyIntensity: 1.0,
      keyColor: 0xfff4e8,
      fillIntensity: 0.5,
      fillColor: 0xffffff,
      topIntensity: 0.35,
      topColor: 0xfff8f0,
      rimIntensity: 0.4,
      rimColor: 0xd8e4ff,
      bounceIntensity: 0.25,
      bounceColor: 0xffd9c4,
    },
    ambientIntensity: 0.55,
    ambientSkyColor: 0xcfd8ff,
    ambientGroundColor: 0x8a7f74,
    environmentIntensity: 0.5,
    shadow: {
      enabled: true,
      mapSize: 2048,
      radius: 4,
      bias: -0.0005,
      normalBias: 0.02,
      opacity: 0.35,
    },
  },
  render: {
    exposure: 1.0,
    toneMapping: 'neutral',
    bloom: { enabled: false, strength: 0.35, radius: 0.6, threshold: 0.85 },
    antialias: true,
    maxPixelRatio: 2,
    targetFps: 60,
  },
  physics: {
    frequency: 60,
    maxSubSteps: 2,
    gravity: 9.8,
    globalAmplitude: 1.0,
    groups: {},
    fallback: { match: [], amplitude: 1.0, stiffness: 60, damping: 6, maxAngleDeg: 30, enabled: true },
  },
  idle: {
    breathRate: 0.22,
    breathDepth: 0.35,
    swayRate: 0.16,
    swayAmount: 0.5,
    postureIntervalMin: 9,
    postureIntervalMax: 22,
    blinkIntervalMin: 2.4,
    blinkIntervalMax: 6.5,
    doubleBlinkChance: 0.08,
    saccadeIntervalMin: 1.2,
    saccadeIntervalMax: 4.0,
  },
  behaviour: {
    intervalMin: 14,
    intervalMax: 34,
    noRepeatWindow: 3,
    busyIntervalScale: 2.0,
  },
  lipSync: {
    attack: 0.55,
    release: 0.3,
    gain: 1.0,
    noiseFloor: 0.04,
    maxWeight: 0.9,
    visemeBlendRate: 10,
  },
};
